### ISSUE TITLE
Manual install using C:\Program Files (x86)\Common Files\Adobe\CEP\extensions

### ISSUE THREAD

**Issue by bradleylancaster** [adobe-photoshop/generator-assets#418]
Hi i unzipped and dropped this plugin here Guide Guide worked for me using the technique this plugin did not work.

Is there a way to install this manually?

Thanks

**Comment by Jolg42** [comment]
Hi @bradleylancaster 

I think you can check this link > [Plug-in locations](https://github.com/adobe-photoshop/generator-core/wiki/Generator-Architecture#plug-in-locations)

Because Generator plugins et other plugins are in fact different and need to be in different folders.

Also there is a special Generator Forum  if you need more help here >
https://groups.google.com/forum/#!forum/adobe-generator-dev

**Comment by mcilroyc** [comment]
Thanks @Jolg42, that's right.  I'm closing this bug, but @bradleylancaster use that Forum link if you have trouble finding the right Generator plugin location.
